version: "3"

services:
  postgres:
    container_name: db_postgresql
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - srcgenerator
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5

  pgadmin:
    container_name: db_pgadmin
    image: dpage/pgadmin4:8.12.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - 5051:80
    depends_on:
      - postgres
    networks:
      - srcgenerator
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

networks:
  srcgenerator:
    driver: bridge

